name: Test

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.20

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Test the code
        run: go test ./...
