name: Test

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Test the code
        run: go test ./...
